### ISSUE TITLE
[Feature Request] Buying Proper VR headset for dev here (Mock HMD XR plugin??)

### ISSUE THREAD

**Issue by brentjohnston** [parkchamchi/DepthViewer#11]
_Edit: Issue closed, I must have turned it on by mistake because when I start a new project it's Mock HMD is not on by default._

I think I have just realized why this app is very lacking in proper VR support with motion controls and positional tracking. is it because it's using the The "Mock HMD XR Plugin for Unity" by default for which is for people building without a device.

I would highly recommend dev doesn't have a headset buying at least a Quest 2 as bare minimum, which can be had for about $150 on used marketplace at the moment, I'd even be willing to donate some money to get you one to get proper VR support in this app. The Quest 3 just came out but is more expensive and a lot better but if money is an issue let me know.

This app has a lot of potential right now.

**Comment by parkchamchi** [comment]
I didn't know Quest 2's price has sunk😅 I actually have a used Dell Visor WMR headset I bought for 185 USD in 2019. Needless to say using WMR headset is pure pain, and I actually had to 3D print to attach my lens. Now that the price of it has become slightly affordable I am tempted to buy one. But I must say that for this repo my WMR headset seems to be sufficient.

I once tried to implement the motion control but I gave up since the system did not recognize the controller click, for the reason to this day I am not sure if it's WMR issue or it's on Unity side.

I may have enabled the Mock HMD in the project, for reason I can't quite remember.
