### ISSUE TITLE
[Feature Request] Seamless video looping in an environment where running server/python is not an option?

### ISSUE THREAD

**Issue by ricardofeynman** [parkchamchi/DepthViewer#8]
When videos loop, there's a momentary drop to black before the video repeats. 

If it's not just my setup that's causing this issue, are there any plans to implement an approach that would result in seamless loops?

In a scenario where image sevrer/python can't be used, is there any way to mitigate this second of blackness?

Thanks.

**Comment by parkchamchi** [comment]
Hi.

That behavior occurred in my environment too and there was another person who reported this issue earlier, so I think this is an Unity issue, caused by Unity's `VideoPlayer` object limitation.
I guess it can be bypassed by saving the last frame (whose framenumber can be known) as `Texture2D` and use it until the video reloads.

I'll try to implement it after say 1-2 weeks (exam period😿)

**Comment by parkchamchi** [comment]
[v0.9.1-beta.3](https://github.com/parkchamchi/DepthViewer/releases/tag/v0.9.1-beta.3)

Turns out using the `VideoPlayer`'s `Pause()` not `Stop()` makes no flickering.

**Comment by ricardofeynman** [comment]
I will test over the weekend and report back. 

Thank you.

**Comment by ricardofeynman** [comment]
My apologies for the delayed update. On my Windows 11 setup the loop now appears seamless for mp4 format videos I have tested with so far. Thanks for this fix.

There is still a very slight dip to black as the video is manually switched to the next video in the directory. I'm not sure if this is to be expected as it does not dip to black when switching between images. However perhaps this could be due to the amount of new data being loaded for every video MiDaS has to process?

I mention this as I'm also searching for a way of getting the video/image content of a directory to play seamlessly, either as linear or random sequences. 

AFAIK the image server has this covered for image sequences, but I'm interested to know for video especially, are there any methods for playing through the contents of a selected directory that you have already implemented, or are exploring for this project? 

My thinking is that I've previously seen VideoPlayer handling seamless transitions between multiple videos played in sequence in other Unity projects, so if the dip to black is not caused by MiDaS, possibly VideoPlayer can cache the initial frames of an array of videos in a way that might allow DepthViewer to render these video sequences seamlessly. 

I'm thinking something like this could be a solution https://stackoverflow.com/questions/47401759/play-different-videos-back-to-back-seamlessly-using-unity-video-player It's an old post but checking the 2021.3 documentation, videoPlayer.Prepare() still appears to be the way this is handled. Any thoughts on whether this approach could work or would the MiDaS model still be a botttleneck when transitioning between videos?

**Comment by parkchamchi** [comment]
Removing the dip-to-black between the videos (using the native VideoPlayer) would be difficult because the code [frees the VideoPlayer resources](https://github.com/parkchamchi/DepthViewer/blob/master/DEPTH/Assets/Scripts/TexInputs/ImgVidDepthTexInputs.cs#L421) when a new input is requested. Curiously enough commenting out the cleanup code (`_vp.Stop()`, `_vp.url = null`) would not remove this behavior, so other methods would be needed, like the one you linked. The one in the link looks promising (`Prepare()` then wait for the `isPrepared` -- or imo `prepareCompleted` event can be used), but it wouldn't be able to applied to this repo.

Side note: MiDaS would not be a bottleneck when transitioning between videos but disk reading and processing the file would be, since the input shape does not change while using the Unity-side inference engines (Barracuda or C#-OnnxRuntime)

**Comment by parkchamchi** [comment]
Thank you.
